name: Daily60s

on:
  schedule:
    - cron: '0 9 * * *'  # 每天 UTC 时间 9:00 运行
  workflow_dispatch:  # 手动触发

jobs:
  send_news:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Fetch News
      run: |
        curl -sL https://api.vvhan.com/api/60s > news.txt

    - name: Print news content
      run: |
        cat news.txt

    - name: Send news to Feishu
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "msg_type": "text",
          "content": {
            "text": "'"$(cat news.txt)"'"
          }
        }' ${{ secrets.FEISHU_WEBHOOK_URL }}
